### PR TITLE
Add global variable argument

### PR DESCRIPTION
**Pull request by EdGuest**
Add an argument to to allow setting of the compiler --global-var option.
This allows the definition of a global variable for the less compilation.

### CODE REVIEW

**Comment by Jehran** [comment]
Can this option be specified multiple times with different parameters?

**Comment by EdGuest** [comment]
Although this was not clear when looking at the lessc documentation, lessc does allow for multiple --global-var arguments and --modify-var arguments. I will take a look providing a revised version to support that.

**Comment by EdGuest** [comment]
I have added a further refinement that allows for multiple global vars, supplied as an array (that you would defined for example in an ItemGroup in the targets file). There is also support for the --modify-var argument in a similar way. I have tested both of these on a project we have ongoing.

**Comment by Jehran** [comment]
This is now in version 1.0.10 which is pushed to NuGet. Thank you for your support.

**Pull request merged**
